--------------------------------------------------------
-- Permisos para paquetes
--------------------------------------------------------

GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_CAMPANA TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_CIUU TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_CONTROL_ENCUESTA TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_DEPARTAMENTO TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_DISTRITO TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_EMPRESA_GAS TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_EMPRESA_IND TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_EMPRESA_LUZ TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_ENCUESTA TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_EXTERNO TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_GIRO TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_GRUPO_EMPRESA TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_INDICADOR TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_INTERNO TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_LOGIN TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_MANTENIMIENTO TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_PAGINA_HOME TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_PARAMETRO TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_PLANTA_EMPRESA TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_PROVINCIA TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_REPORTE TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_ROL TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_TABLA_MAESTRA TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_USUARIO TO SISCEUSI;
GRANT EXECUTE ON SISCEUSI.PKG_SISCEUSI_ZONA TO SISCEUSI;
