ALTER TABLE SISCEUSI.T_GENM_EMPRESA_INDUSTRIA
MODIFY dni VARCHAR2(30);

--ACTUALIZAR PACKAGE PKG_SISCEUSI_CONTROL_ENCUESTA

--========================================================
--ACTUALIZACION 29-10-2022
ALTER TABLE SISCEUSI.T_GENM_EMPRESA_INDUSTRIA
ADD observacionUno VARCHAR2(250);
ALTER TABLE SISCEUSI.T_GENM_EMPRESA_INDUSTRIA
ADD observacionDos VARCHAR2(250);
ALTER TABLE SISCEUSI.T_GENM_EMPRESA_INDUSTRIA
ADD observacionTres VARCHAR2(250);

--ACTUALIZAR PACKAGE PKG_SISCEUSI_EMPRESA_IND
--ACTUALIZAR PACKAGE PKG_SISCEUSI_PLANTA
--ACTUALIZAR PACKAGE PKG_SISCEUSI_USUARIO
--ACTUALIZAR PACKAGE PKG_SISCEUSI_CAMPANA